### ISSUE TITLE
"error writing output file" on MP4 without audio

### ISSUE THREAD

**Issue by torridgristle** [CrushedPixel/moshpit#1] opened 2020-11-26 03:32 UTC
Says ```Error: error writing output file: exit status 1``` and the log reads
```
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\J\Documents\Image Editing\moshpit\rotate1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2020-11-26T03:28:57.000000Z
    encoder         : HandBrake 1.3.2 2020050300
  Duration: 00:00:20.00, start: 0.000000, bitrate: 789 kb/s
    Stream #1:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 512x512 [SAR 1:1 DAR 1:1], 786 kb/s, 24 fps, 24 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2020-11-26T03:28:57.000000Z
      handler_name    : VideoHandler
Stream map '1:a:0' matches no streams.
To ignore this, add a trailing '?' to the map.
```

**Comment by makew0rld** [comment] 2020-11-26 23:12
(Not the author of this repo.)

This likely caused by the file without audio as you mention in the title of the issue. The problem lines of code are here:

https://github.com/CrushedPixel/moshpit/blob/30149992ea99d7a4e7b1bab21ebd360907a0cb5a/convert.go#L126-L128

I've [fixed](https://github.com/makeworld-the-better-one/moshpit/commit/f22afc82d56e6c07ec14b00ad176362ff10b45d1) this in [my fork](https://github.com/makeworld-the-better-one/moshpit). Let me know if you would like a executable to run, I will upload one here. Just tell me your OS and whether it's 32-bit or 64-bit.

**Comment by torridgristle** [comment] 2020-11-27 13:45
Windows 10, 64-bit. Thanks.

**Comment by makew0rld** [comment] 2020-11-27 13:50
Here you go! Download this, right-click and unzip it, then run the unzipped exe. Let me know if you have any problems.

[moshpit.exe.zip](https://github.com/CrushedPixel/moshpit/files/5608092/moshpit.exe.zip)

**Comment by torridgristle** [comment] 2020-11-27 14:35
Thank you, this really helps me out.

**Comment by CrushedPixel** [comment] 2020-11-29 02:06
@makeworld-the-better-one Feel free to create a PR with your changes, I'll happily merge them into this repo :)

**Comment by makew0rld** [comment] 2020-11-29 02:10
@CrushedPixel It's basically just a one character change, see [this commit](https://github.com/makeworld-the-better-one/moshpit/commit/f22afc82d56e6c07ec14b00ad176362ff10b45d1). Just add a question mark to the end of line 128 in `convert.go`.

Also in my fork, I use Go modules. Are you interested in that being merged upstream?

**Comment by CrushedPixel** [comment] 2020-11-29 03:50
Yes, I am interested in the update to Go modules, as well.
I haven't written any Go code in quite some time, but I remember being very excited when Go modules were on the horizon.

I've seen in your fork that you're potentially interested in adding features to this fork - I'd be happy to add you as a maintainer to this repository if you like :)

**Comment by makew0rld** [comment] 2020-11-29 06:00
> I'd be happy to add you as a maintainer to this repository if you like

Thanks! That's nice of you. My first action would be to sync things up with my fork, so adding Go modules support and this fix. After that, I probably wouldn't do much, although eventually I'd like to develop the library aspect of this more, see what features can be added or bugs fixed. Just can't commit to that now. If that sounds okay to you I'd be happy to be added as maintainer.

**Comment by CrushedPixel** [comment] 2020-12-02 01:45
In that case, we can just address the Go modules and the fix with 2 separate PRs, and in case you ever want to do more development you can let me know and I'll make you a maintainer :)

**Comment by makew0rld** [comment] 2020-12-02 19:06
Works for me! I made just one PR if that's okay, see #2.

**Closed as completed** 2020-12-10 12:46 UTC
